name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python 3.11.5
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    # Cache Python dependencies
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt for dependencies

    - name: Access Secret Key
      env:
        MY_SECRET_KEY: ${{ secrets.DAGSHUB_PAT }}
      run: |
        dvc repro


    # Additional steps can be added here (e.g., testing, linting, etc.)
